# Generated by Django 4.1 on 2023-05-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cID", models.TextField(max_length=10, verbose_name="卡牌编号")),
                ("cName", models.TextField(max_length=10, verbose_name="卡牌名称")),
                ("cCost", models.TextField(max_length=20, verbose_name="费用")),
                ("cEffect", models.TextField(max_length=50, verbose_name="卡牌效果")),
                ("cStory", models.TextField(max_length=50, verbose_name="卡牌趣闻")),
                (
                    "cImg",
                    models.ImageField(blank=True, upload_to="card/", verbose_name="原画"),
                ),
            ],
            options={
                "verbose_name": "卡牌",
                "verbose_name_plural": "卡牌",
            },
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Fdiscription",
                    models.CharField(default=" ", max_length=40, verbose_name="文件描述"),
                ),
                ("FField", models.FileField(upload_to="file/", verbose_name="文件")),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
            },
        ),
    ]
